# Generated by Django 4.1.4 on 2022-12-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification_card',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rfc_equivalet',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
