# Generated by Django 4.1.4 on 2022-12-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payroll_filename',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
